<a href="https://colab.research.google.com/github/sachinthadilshann/pytorch_youtube_course_by_DanielBourke/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to tensors

In [1]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt

In [66]:
print(torch.__version__)

2.8.0+cu126


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
Matrix = torch.tensor([[1,2],
 [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
tensor = torch.tensor([[[1,2,3],
                       [3,4,5],
                       [2,3,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 3, 5]]])

In [10]:
tensor.shape

torch.Size([1, 3, 3])

In [11]:
tensor.ndim

3

## Random tensors

In [12]:
random_tensor = torch.rand(4,2)
random_tensor

tensor([[0.7061, 0.8617],
        [0.0233, 0.4157],
        [0.0464, 0.7840],
        [0.6901, 0.1719]])

In [13]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [14]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

##Creating a range and tensors like

In [17]:
torch.range(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [18]:
one_to_ten = torch.arange(start=1, end=1000, step=100)
one_to_ten

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [19]:
ten_zeors = torch.zeros_like(input=one_to_ten)
ten_zeors

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [20]:
float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype = None ,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 4., 5.])

In [21]:
float_32_tensor.dtype

torch.float32

In [22]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [23]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [24]:
int_32_tensor = torch.tensor([1,3,7],dtype=torch.long)
int_32_tensor

tensor([1, 3, 7])

In [25]:
float_32_tensor * int_32_tensor

tensor([ 3., 12., 35.])

In [26]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3950, 0.9273, 0.3861, 0.7756],
        [0.3701, 0.6384, 0.1240, 0.7430],
        [0.6931, 0.7660, 0.5070, 0.9046]])

In [27]:
print(some_tensor)
print(f'Datatye of Tensor :{some_tensor.dtype}')
print(f'Shape of Tensor :{some_tensor.shape}')
print(f'Device of Tensor :{some_tensor.device}')

tensor([[0.3950, 0.9273, 0.3861, 0.7756],
        [0.3701, 0.6384, 0.1240, 0.7430],
        [0.6931, 0.7660, 0.5070, 0.9046]])
Datatye of Tensor :torch.float32
Shape of Tensor :torch.Size([3, 4])
Device of Tensor :cpu


## Manipulating Tensors

In [28]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
tensor * 10

tensor([10, 20, 30])

In [30]:
tensor - 1

tensor([0, 1, 2])

In [31]:
#torch in-built functions

torch.add(tensor,10)

tensor([11, 12, 13])

In [32]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [33]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

## Matrix Multiplication

In [34]:
print(tensor,'*',tensor)
print(f'Equals :{tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :tensor([1, 4, 9])


In [35]:
torch.matmul(tensor,tensor)


tensor(14)

In [36]:
print(1*1 + 2*2 + 3*3)

14


In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.64 ms, sys: 0 ns, total: 1.64 ms
Wall time: 4.07 ms


In [38]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 418 µs, sys: 0 ns, total: 418 µs
Wall time: 1.06 ms


tensor(14)

## Tensor Aggregation

In [39]:
x = torch.arange(0,100,10)
x.dtype

torch.int64

In [40]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [41]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [42]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [43]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
x.argmin()

tensor(0)

In [45]:
x.argmax()

tensor(9)

In [46]:
x[9]

tensor(90)

In [47]:
x  = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
x.dtype

torch.float32

In [49]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [50]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
x_reshape = x.reshape(3,3)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [52]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [55]:
x_reshape.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [56]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Selecting Data From Tensors (Indexing)

In [57]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [58]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
x[0][0]

tensor([1, 2, 3])

In [60]:
x[0][0][0]

tensor(1)

In [61]:
x[0][1]

tensor([4, 5, 6])

In [62]:
x[:,0]

tensor([[1, 2, 3]])

In [63]:
x[:,:,1]

tensor([[2, 5, 8]])

## PyTorch Tensors and NumPy


In [64]:
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [65]:
array.dtype

dtype('float64')

In [67]:
torch.arange(1.0,8.0).dtype

torch.float32

In [68]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
#tensor to Numpy Array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [71]:
tensor  = tensor +1
tensor

tensor([2., 2., 2., 2., 2., 2., 2.])

## Reproducbility

In [72]:
torch.rand(3,3)

tensor([[0.1596, 0.6586, 0.0167],
        [0.5249, 0.3042, 0.3318],
        [0.1332, 0.7791, 0.0128]])

In [73]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2177, 0.2944, 0.5588, 0.9868],
        [0.0230, 0.0691, 0.2906, 0.9005],
        [0.1461, 0.0157, 0.9529, 0.7363]])
tensor([[0.6747, 0.0475, 0.6332, 0.1634],
        [0.6712, 0.7380, 0.2527, 0.8945],
        [0.6666, 0.2569, 0.9177, 0.7522]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [77]:
RANDOM_REED = 43

torch.manual_seed(RANDOM_REED)
random_tensor_C = torch.rand(3,4)

print(random_tensor_C)

torch.manual_seed(RANDOM_REED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
