<a href="https://colab.research.google.com/github/sachinthadilshann/pytorch_youtube_course_by_DanielBourke/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to tensors

In [2]:
import torch
import pandas as ps
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.5.1+cu121


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
vector = torch.tensor([2,2])
vector

tensor([2, 2])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
Matrix = torch.tensor([[1,2],
 [3,4]])
Matrix

tensor([[1, 2],
        [3, 4]])

In [10]:
tensor = torch.tensor([[[1,2,3],
                       [3,4,5],
                       [2,3,5]]])
tensor

tensor([[[1, 2, 3],
         [3, 4, 5],
         [2, 3, 5]]])

In [11]:
tensor.shape

torch.Size([1, 3, 3])

In [12]:
tensor.ndim

3

#Random tensors

In [13]:
random_tensor = torch.rand(4,2)
random_tensor

tensor([[0.9220, 0.5081],
        [0.5676, 0.8487],
        [0.2089, 0.9454],
        [0.5323, 0.5135]])

In [14]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [15]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

#Creating a range and tensors like

In [18]:
torch.range(0,10)

<ipython-input-18-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [19]:
one_to_ten = torch.arange(start=1, end=1000, step=100)
one_to_ten

tensor([  1, 101, 201, 301, 401, 501, 601, 701, 801, 901])

In [20]:
ten_zeors = torch.zeros_like(input=one_to_ten)
ten_zeors

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [21]:
float_32_tensor = torch.tensor([3.0,4.0,5.0],
                               dtype = None ,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 4., 5.])

In [22]:
float_32_tensor.dtype

torch.float32

In [23]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16)

In [24]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [25]:
int_32_tensor = torch.tensor([1,3,7],dtype=torch.long)
int_32_tensor

tensor([1, 3, 7])

In [26]:
float_32_tensor * int_32_tensor

tensor([ 3., 12., 35.])

In [27]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3442, 0.2652, 0.3749, 0.2723],
        [0.3191, 0.2648, 0.1214, 0.6770],
        [0.9024, 0.2047, 0.4906, 0.9789]])

In [28]:
print(some_tensor)
print(f'Datatye of Tensor :{some_tensor.dtype}')
print(f'Shape of Tensor :{some_tensor.shape}')
print(f'Device of Tensor :{some_tensor.device}')

tensor([[0.3442, 0.2652, 0.3749, 0.2723],
        [0.3191, 0.2648, 0.1214, 0.6770],
        [0.9024, 0.2047, 0.4906, 0.9789]])
Datatye of Tensor :torch.float32
Shape of Tensor :torch.Size([3, 4])
Device of Tensor :cpu


# Manipulating Tensors

In [29]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
tensor * 10

tensor([10, 20, 30])

In [31]:
tensor - 1

tensor([0, 1, 2])

In [32]:
#torch in-built functions

torch.add(tensor,10)

tensor([11, 12, 13])

In [33]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [34]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

# Matrix Multiplication

In [35]:
print(tensor,'*',tensor)
print(f'Equals :{tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :tensor([1, 4, 9])


In [36]:
torch.matmul(tensor,tensor)


tensor(14)

In [37]:
print(1*1 + 2*2 + 3*3)

14


In [38]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.9 ms, sys: 0 ns, total: 1.9 ms
Wall time: 1.82 ms


In [39]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 348 µs, sys: 0 ns, total: 348 µs
Wall time: 290 µs


tensor(14)

# Tensor Aggregation

In [40]:
x = torch.arange(0,100,10)
x.dtype

torch.int64

In [41]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [42]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [43]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [44]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [46]:
x.argmin()

tensor(0)

In [47]:
x.argmax()

tensor(9)

In [48]:
x[9]

tensor(90)

In [53]:
x  = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
x.dtype

torch.float32

In [58]:
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [59]:
x_reshape = x.reshape(1,9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [60]:
x_reshape = x.reshape(3,3)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [61]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [63]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [65]:
x_reshape.squeeze()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [67]:
x_original = torch.rand(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))